variables:
    PYTHON_VERSION: python:3.11

image: $PYTHON_VERSION

stages:
    - build
    - test
    - deploy
    - release

api-build:
    stage: build
    script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install --upgrade pip
        - pip install -r fastapi-pytest/requirements.txt
    tags:
        - cicd-dev
        
api-test:
    stage: test
    script:
        - echo 'this is unit test stage'

api-deploy:
    stage: deploy
    script: 
        - echo 'this is deployment stage'

api-release:
    stage: release
    script:
        - echo 'this is release of app'
